#!/bin/sh
htpasswd -bc /etc/squid3/users "${SQUID_USERNAME}" "${SQUID_PASSWORD}"
CHOWN=$(/usr/bin/which chown)
SQUID=$(/usr/bin/which squid)
"$CHOWN" -R proxy:proxy /var/log/squid
"$CHOWN" -R proxy:proxy /var/spool/squid
"$CHOWN" -R proxy:proxy /var/log/squid3

sed -i '/^#/d' "/etc/squid/squid.conf"
sed -i '/^$/d' "/etc/squid/squid.conf"

sed -i "s/^http_port\(.*\)/http_port $SQUID_PORT/g" "/etc/squid/squid.conf"

exec squid3 -N $*
